name: Build Flutter APK

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: []

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      # Set up Flutter.
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.16.9"
          channel: "stable"
      #- run: flutter doctor -v

      # Checkout the repository code and get packages.
      - name: Checkout flutter_app code
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"

      - name: Build APK
        run: flutter build apk --release

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: release-apk
          path: build/app/outputs/apk/

      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          tag: test_apk.${{github.run_number}}
          artifacts: "build/app/outputs/apk/release/*.apk"
